'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _exit() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_exit", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property _select() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_select", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Arrows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Arrows2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrows2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("back", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Background2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bar_Layout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bar_Layout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bar_Layout1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bar_Layout1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close_Fullscreen_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_Fullscreen_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close_Fullscreen_Button_highlighted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_Fullscreen_Button_highlighted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Exit_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Exit_Button_Highlighted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit_Button_Highlighted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Exit_Button_Pushed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit_Button_Pushed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fullscreen_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fullscreen_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fullscreen_Button_Highlighted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fullscreen_Button_Highlighted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fullscreen_Button_Highlighted1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fullscreen_Button_Highlighted1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LoadingScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadingScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Maximize_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maximize_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Maximize_Button_Highlighted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maximize_Button_Highlighted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Maximize_Button_Pushed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maximize_Button_Pushed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Minimize_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minimize_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Minimize_Button_Highlighted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minimize_Button_Highlighted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Minimize_Button_Pushed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minimize_Button_Pushed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Next_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Next_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Next_Button_Highlighted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Next_Button_Highlighted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pause_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pause_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pause_Button_Highlighted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause_Button_Highlighted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pause_Button1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause_Button1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play_Button_Highlighted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_Button_Highlighted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play_Button_Normal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_Button_Normal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Previous_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Previous_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Previous_Button_Highlighted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Previous_Button_Highlighted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rejected() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("rejected", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Resolution_1280x800() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Resolution_1280x800", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Resolution_1280x800_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Resolution_1280x800_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Resolution_1366x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Resolution_1366x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Resolution_1366x768_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Resolution_1366x768_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Resolution_1920x1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Resolution_1920x1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Resolution_1920x1080_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Resolution_1920x1080_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Shuffle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shuffle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vista_window_demo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vista_window_demo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vista_window_demo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vista_window_demo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vista_window_demo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vista_window_demo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vista_window_demo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vista_window_demo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VLCBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VLCBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
